// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAPLl6CqbxmaLHCweCNc7BbsX0EMMQKF8',
    appId: '1:556342312134:web:1dabf3b4bfa0fd41022bc7',
    messagingSenderId: '556342312134',
    projectId: 'cal-track-ai',
    authDomain: 'cal-track-ai.firebaseapp.com',
    storageBucket: 'cal-track-ai.firebasestorage.app',
    measurementId: 'G-XYD1TGFPF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChUY5k3_jYnGOtsp5JbP5mIE-3eYyCIRM',
    appId: '1:556342312134:android:9d0b0df8756bfd27022bc7',
    messagingSenderId: '556342312134',
    projectId: 'cal-track-ai',
    storageBucket: 'cal-track-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAooZVswPi-r8Lw7q86sUY6kCyZKp5W3dw',
    appId: '1:556342312134:ios:cebb7a93851666fd022bc7',
    messagingSenderId: '556342312134',
    projectId: 'cal-track-ai',
    storageBucket: 'cal-track-ai.firebasestorage.app',
    androidClientId: '556342312134-vdivhshn2ji8cgibofgsd5qlkjpaa39b.apps.googleusercontent.com',
    iosClientId: '556342312134-78u1ptrn0o79mneg272g0nka0f4ihcol.apps.googleusercontent.com',
    iosBundleId: 'com.FivePointAILabs.caltrackai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAooZVswPi-r8Lw7q86sUY6kCyZKp5W3dw',
    appId: '1:556342312134:ios:cebb7a93851666fd022bc7',
    messagingSenderId: '556342312134',
    projectId: 'cal-track-ai',
    storageBucket: 'cal-track-ai.firebasestorage.app',
    androidClientId: '556342312134-vdivhshn2ji8cgibofgsd5qlkjpaa39b.apps.googleusercontent.com',
    iosClientId: '556342312134-78u1ptrn0o79mneg272g0nka0f4ihcol.apps.googleusercontent.com',
    iosBundleId: 'com.FivePointAILabs.caltrackai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAPLl6CqbxmaLHCweCNc7BbsX0EMMQKF8',
    appId: '1:556342312134:web:b3a2978c8d3ee030022bc7',
    messagingSenderId: '556342312134',
    projectId: 'cal-track-ai',
    authDomain: 'cal-track-ai.firebaseapp.com',
    storageBucket: 'cal-track-ai.firebasestorage.app',
    measurementId: 'G-CQM2DGLHEN',
  );
}
